[settings]
idiomatic_version_file_enable_tools = []

[tools]
cue = "0.14.1"
fd = "10.3.0"
opentofu = "1.10.6"
podman = "5.6.1"
prek = "0.2.20"
sops = "3.11.0"
uv = "0.9.17"

[tasks.setup]
run = "uv run install.py"
