caddyfile_auth_user: ENC[AES256_GCM,data:TNyfWOE=,iv:DTngxkSMyrKkNpzXn4VZIqd7UXakJMkLD3FkLuntilI=,tag:1RXLxH8cXpSxewTY/pUrLA==,type:str]
caddyfile_auth_pass: ENC[AES256_GCM,data:z63Taep6ULwCCtgQeovEzYOLuW5LdGicXtIJDqpmhZSkC7p5xMzQgt6ZYZP1SSyLldyDO1nL5M1VzVW4bWzhKxs3KNWWGAG0B2QsSCM1svQ=,iv:M9vfH+ydEN13GtZsyyVftQSkNbDADFViwX0oApkRrVQ=,tag:e+6cSGMvvBXlmKke/TfDBg==,type:str]
caddyfile_auth_token: ENC[AES256_GCM,data:lbCVkD+zmMsnV8WqBunPfl65KZls/ewh1CsfhQXAOeoqlkde,iv:xHFMphw5Sho/MYmwgfnWJnZRgmHrfU+qziHn+SYRqgA=,tag:JO8FtxbGYeHeJjPFYHNNog==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19ycrg4v57swrmzsuffwxlrw7ld26wfttxag3r7qwqq4jaatdeeeq9kmsu2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmYndYVnR3OXVsMDk1dUJJ
            dXplaExkaFhEMmR4eVhTOUdIQ2xnajR5T2lBCmtBL0g3eEZVNUszaDlWYWo5Qk5w
            WW1wMmpGaVc4YUJDNnQxc1J0a3NzV0kKLS0tIFUxeUZEbUtFVHIzT2ZCYjRjemJK
            NVFTc2NXdkJWUUo1dTlwNENUOXJVT1kKSLU0kBDyViaTLoyF76jShsOd21SFNngk
            Ez1GQtVUd271ufVDYQUz+SGBh2Nch/VwkPXVmOzy434guwB6eW6LxA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-19T07:56:34Z"
    mac: ENC[AES256_GCM,data:O71ShUS6/q0/5mOSrLjPaEGvCIGs27ROqKBJFZriuZbrI/h6/iokDx+SeN/3kjJzWo/PJPOaZ3P1nFtN754CF01Ly+7FsdxgGs1Tn8QK2eMrDvFu6CxxmNLVQkQeNPqxVeyXD07HF/lkZbdHxJZM834v2X/n4POuRotgXOu4av4=,iv:Pxkclzsi60XdTCFX1cvgV3+yPRYzQNECMydJjngzkSY=,tag:XFV5TlKD+J4ZOHl/VmI8pQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
