global_disks_data: ENC[AES256_GCM,data:h7ZdYsPZufcOax1VAy0Rimom9yguRBk=,iv:KBEovowovk9rDFNIoKLKTByDPLV9/o7D3hexh4ChToI=,tag:HsJ/KWjUmzBDqlrPVSjc1g==,type:str]
global_disks_storage_path: ENC[AES256_GCM,data:F9AZZF8MZXEfDq2uVOrxodh+RYWoVpY=,iv:6XnQK2h1/o/d/BxPMDrFfbWsXc4eHY+RDuUOlaAJsLE=,tag:uJZPGFQFMX038Oa24/KV1Q==,type:str]
global_media: ENC[AES256_GCM,data:SIJeuhIIhoHRMra4hYEKZXtE1tB3hRNWyCk=,iv:9+MMrJCGTBdndxzN87LQyKmGcXoKxWRFpwVIOh7wqgw=,tag:mhVLLfad7NJK4afea+si/A==,type:str]
global_download: ENC[AES256_GCM,data:XakrzlLBc8q3xUIU6y9elJ2SmtmfuBHsQwzAmi5jOaWKsxG/,iv:7eP08cNvzju799w8lMGcg9I2mZfazoxpR4achOfVKSY=,tag:QgDK4cHK34NaemV62aBgpA==,type:str]
global_storage: ENC[AES256_GCM,data:YxaaxBaXLkPKzUmZ,iv:F9XGLO1Xe22WBSZxwW8GXlpqwS3Jf06SmWnR3m82FYk=,tag:jvL9W6S9nS2pe3PoOkaI+A==,type:str]
global_storage_medusa_path: ENC[AES256_GCM,data:QMvIEgdMl9SG9DgQJujRRdRtVcdl5NwKShgON5fD3y1ijy/reTU=,iv:teQThpC3uOyc3yri4vfjdbvVtu6eH267/sy+xxDR8xo=,tag:R37tYU6zV+90QwKLyP8JJA==,type:str]
global_storage_video_path: ENC[AES256_GCM,data:sDwx4hDR/CmNDpWyKcSnTcmg4g==,iv:JLpLTBXjiZfEqmA6PXWAZVxuhhyBvn3k+YbpVgMuXSs=,tag:ysWFkPIvuoNs0YKqgoCMGQ==,type:str]
global_storage_mergerfs_mkdir_paths:
    - ENC[AES256_GCM,data:Tv1cNfkHYPORYzLcsfn4A8DrHRzphgXlcbA2yGPxxx0=,iv:/RttRGdaobQXtKODGPMRrUp97IkV0NsUlwjZB8D7SVo=,tag:/wraXvnAR/7FXk4E1T2KUA==,type:str]
    - ENC[AES256_GCM,data:5hb/dJHiQ+CmTfTUCEp/IwVaRlrB70wuzv2iZeREuA==,iv:ZBrI43EgZe336VPAU3/rlNfuV0vu2BkB2xJ00VFFlNU=,tag:ylYVp1Ffpz/YQ77ms3txyg==,type:str]
global_volume_path: ENC[AES256_GCM,data:lTBtzW2SRiwfXEJB6CtIyMLklS+XWVI9oCl1oN4=,iv:nvvCKV6p+jKW9wNVpLtczsSttkLVNjgj+tKSnvT386c=,tag:qibcuQTw5qw4O02QNK5f2Q==,type:str]
dynv6_zone: ENC[AES256_GCM,data:+vurnpF4If0g5xLVEwFAPQ==,iv:SecgDx092quh03B4Bc+aB1OIRNLBN754Xs8yR3nHxv0=,tag:147+vFeLwdkxCJbeN0D3Tw==,type:str]
server_subdomain: ENC[AES256_GCM,data:BdXwm90U,iv:SEyqSQeqk+3wSruev+wrbTM2DyIKT1ETP5OViok3oPc=,tag:UdIS2lC11/79FnOUavACbg==,type:str]
server_domain: ENC[AES256_GCM,data:0OwKTVwSv1QjTacJOwlT0jscYjCwUEE7dXh13aBOWGj35VVDpK6y,iv:N8T+kul4DtE0YuXzynO2u0oBsex0ap5gnJl7d4qHoEk=,tag:hGjDdhjAVkqppfWHJYoIxw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19ycrg4v57swrmzsuffwxlrw7ld26wfttxag3r7qwqq4jaatdeeeq9kmsu2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvQ09sc013ZjRXU3hnckVY
            UDVyU3BEK1hnbUZKMWd0OENIS1drMS9lYWpZCmNnR3NoMTQxMmQvMUlWVGhXbTNT
            c0oyUGZhUmxnbEUwYTJYdVdKcWtZTDgKLS0tIHQ0TkFpeW9WS2tQNGlsV0g0dG5z
            VThOQW9MMTAxSEVoajV2THNKVzIzTzQKmrdW59KzTRqlhPhXCiKg6AfCRJc+wQFN
            X+y/8aa4S4ChOK+scFnzsA5q0A8aNWx1pR5l/mWnthhgdLdVEqJ82Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-03T09:39:06Z"
    mac: ENC[AES256_GCM,data:pz0qCV12lcBFPL16xekNJatoB+MeePEvPrdGzTTadBP5cebk/fecPTfjjXQ7DojVVjJRRA/41mkTeYtPP/52NJkFD/ihFW2Zys1s4uQH2uk9rHdJ9i0xSK3wKgwMSJBROMIOWrBxHdOW7ufj7hKZMJjpenBsONsx85jOBK6xbX8=,iv:Epk3KSJohqKHvdrqfFMKfQS/4ly4YJLbOslV7Bh372o=,tag:lzoYGjQt2M5nFI03LYyxhQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
